# Generated by Django 4.0.6 on 2022-07-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamers',
            name='imagen',
            field=models.ImageField(upload_to='servicios'),
        ),
    ]
